# -*- coding: utf-8 -*-
"""APPM4560HW5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qGaTibswnoNSh-4h4ARwmTZeV1k1jhr
"""

## Problem 2 Part c & d
import numpy as np
import matplotlib.pyplot as plt


a = 0.04
b = 0.16
K = 0.1
S = np.array([1, 2, 3, 4, 5])
steps = 10**6
x0 = 0
counts = np.zeros(5)
P = np.zeros((5, 5))


def f(n, a, b):
  pi_n = np.exp((a - b) * n * (n - 1) / 2)
  return pi_n



for i in range(0, 5):
  n = i + 1
  p = 0
  q = 0


  if n < 5:
    p = K * np.exp(a * n)
    P[i, i + 1] = p

  if n > 1:
    q = K * np.exp(b * (n - 1))
    P[i, i - 1] = q

  P[i, i] = 1 - p - q

el, ev = np.linalg.eig(P.T)
el1 = np.argmin(np.abs(el - 1.0))



pi = np.real(ev[:, el1])
pi /= np.sum( pi )

theory = np.array([f(i, a, b) for i in S])
pi_theory = theory / np.sum(theory)


state = x0

for _ in range( steps ):
  counts[state] += 1
  state = np.random.choice(5, p=P[state])

sim = counts / steps



x = np.arange(1, 6)
bw = 0.1

plt.bar(x - bw, sim, width=bw, color='orange', label='Simulation')
plt.bar(x, pi_theory, width=bw, color='blue', label='Theory',)
plt.bar(x + bw, pi , width=bw, color='red', label='Numerical' )

plt.xlabel('State')
plt.ylabel('Probability)')
plt.title('Simulated Theory vs Numerical')

plt.legend()
plt.show()

## Problem 3 part e
x0 = 0
a = 0.99
N1 = 1000
N2 = 10000
P = np.array([[ 1-a, a, 0 ],[ a, 0, 1-a ],[ 0, 1-a, a ]])
el, ev = np.linalg.eig(P.T)
q0 = np.array([1, 0, 0])
c = np.linalg.solve(ev, q0)
steps = np.arange(100)

def g(n):
    D = np.diag(el**n)
    q = ev @ D @ c
    return q[0].real

def build( N ):
  gList = []
  states = np.full(N, x0)
  for n in range( 100 ):
    frac = np.mean( states == 0 )
    gList.append(frac)

    for i in range(N):
      states[i] = np.random.choice([0, 1, 2], p=P[states[i]])
  return gList


gList2 = build( N2 )
gList1 = build( N1 )
theory = [ g(n) for n in range(0,100) ]



plt.plot( steps , gList1, color='black', label=f'Simulation')
plt.plot( steps, theory, color='blue', label='Theory',)
plt.axhline(y=1/3, color='red', label='pi')

plt.title(f'Convergence 1,000')
plt.xlabel('Step')
plt.ylabel('Probability of Being In State 1')
plt.legend()
plt.show()



plt.plot( steps , gList2, color='black', label=f'Simulation')
plt.plot( steps, theory, color='blue', label='Theory',)
plt.axhline(y=1/3, color='red', label='pi')

plt.title(f'Convergence 10,000')
plt.xlabel('Step')
plt.ylabel('Probability of Being In State 1')
plt.legend()
plt.show()